'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminSanPham_old

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''loading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loading As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''panelAax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelAax As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cmbLocNhomSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLocNhomSP As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbLocHangSX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLocHangSX As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbLocNguoiDang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLocNguoiDang As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbTrangThai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTrangThai As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtTuNgay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTuNgay As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtDenNgay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDenNgay As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''cmbSapXepThoiGian control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSapXepThoiGian As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtTimKiem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimKiem As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnTemSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTemSP As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnTaiLai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTaiLai As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''radTabSp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radTabSp As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''radMutilPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radMutilPage As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''pageSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageSerial As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''gdvSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvSerial As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pageModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageModel As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''gdvModels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvModels As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''panelThemSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelThemSP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btLuuTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btLuuTop As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btHuyTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btHuyTop As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''lblTieuDeTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTieuDeTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblThoiGianCapNhat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThoiGianCapNhat As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ID_Serie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_Serie As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Ten_Serie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ten_Serie As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ID_SanPham control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_SanPham As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LST_HinhAnh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LST_HinhAnh As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LST_Files control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LST_Files As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtTenVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTenVN As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtTenEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTenEN As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModel As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cmbHangSX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHangSX As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbXuatXu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbXuatXu As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbNhomSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNhomSP As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cmbTinhTrang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTinhTrang As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtGiaBan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGiaBan As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''sqlData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlData As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtHoTroH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoTroH As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''txtMoTaVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoTaVN As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtMoTaEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoTaEN As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lstHinhAnh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstHinhAnh As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''RadDataPager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDataPager1 As Global.Telerik.Web.UI.RadDataPager

    '''<summary>
    '''btnUploadHinhAnh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadHinhAnh As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''btnAnhChinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnhChinh As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnXoaAnh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXoaAnh As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rTabNoiDung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rTabNoiDung As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''rMultiPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rMultiPage As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''txtNoiDungVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoiDungVN As Global.AdminBaoAn.BAOAN_EDITTOR

    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''txtNoiDungEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoiDungEN As Global.AdminBaoAn.BAOAN_EDITTOR

    '''<summary>
    '''txtTuKhoaSEO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTuKhoaSEO As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtMoTaSEO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoTaSEO As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkIsSEO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsSEO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lstFileTaiLieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstFileTaiLieu As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnUploadFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadFile As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''btnTaiFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTaiFile As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnXoaFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXoaFile As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnLuuBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLuuBottom As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnHuyBotom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHuyBotom As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rThongBao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rThongBao As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RadWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow
End Class
