'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminSetColorPage
    
    '''<summary>
    '''PanelColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelColor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtNenChinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNenChinh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTopMXH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopMXH As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTopMXH_hover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTopMXH_hover As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChu_Top_GioiThieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChu_Top_GioiThieu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNen_Top_GioiThieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNen_Top_GioiThieu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChu_Top_GioiThieu_Hover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChu_Top_GioiThieu_Hover As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNen_Top_GioiThieu_Hover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNen_Top_GioiThieu_Hover As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClick_GioiThieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClick_GioiThieu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChu_TrangChu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChu_TrangChu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNen_TrangChu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNen_TrangChu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChu_TrangChu_Hover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChu_TrangChu_Hover As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNen_TrangChu_Hover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNen_TrangChu_Hover As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtbottom_DangDuocQuanTam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbottom_DangDuocQuanTam As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtbottom_DuAnMoi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbottom_DuAnMoi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''buttonGetColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonGetColor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSaveColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveColor As Global.System.Web.UI.WebControls.Button
End Class
